#!/usr/bin/env python3
"""
Billnaw build — concatenate src/ modules into billnaw.js and billnaw.css.

    python3 build.py            build
    python3 build.py --check    verify the bundles are up to date (for CI)

ORDER IS LOAD-BEARING. Each module patches functions defined by the ones before
it. Reordering does not raise an error; it silently changes behaviour.
"""
import sys, os, hashlib, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'src')

JS = [
    ('billnow-addon.js',          'Bluetooth thermal printing, storage hardening, premium chrome'),
    ('billnow-fixes.js',          'Correctness fixes for defects in app.js (FIX 1-10)'),
    ('billnow-print.js',          'Print router: thermal / A4 / PDF, GST copies'),
    ('billnow-ui.js',             'Counter UI: the amount ladder, balance states'),
    ('billnow-mobile.js',         'Mobile app shell: app bar, cards, quick actions'),
    ('billnow-print-industry.js', 'Per-trade invoice blocks (drug licence, HUID, serials)'),
    ('billnow-invoice.js',        'Four sector invoice layouts incl. pharmacy fanfold'),
    ('billnow-nav.js',            'Drawer navigation, customer sheet, sales analysis'),
    ('billnow-brand.js',          'Billnaw brand, shop-name headings, sector menu'),
    ('billnow-flow.js',           'Legacy 3-step flow (stands down beside the native checkout)'),
    ('billnow-picker.js',         'Product picker, shop logo, grouped settings'),
    ('billnow-pro.js',            'Print isolation, paid-in-full, printer setup, Rule 46'),
    ('billnow-checkout.js',       'Checkout consolidation: who and how, inside the app modal'),
    ('billnow-final.js',          'Scanner preview, thermal logo, export, khata, install'),
    ('billnow-ops.js',            'Sales filter, serial entry, edit safety, diagnostics'),
    ('billnow-native.js',         'Capacitor bridge (inert in a browser)'),
]

CSS = [
    ('billnow-addon.css',          'Premium chrome, toasts, mobile ergonomics'),
    ('billnow-print.css',          'A4 page geometry, repeating headers, GST copies'),
    ('billnow-ui.css',             'The amount ladder, tabular numerals'),
    ('billnow-mobile.css',         'App bar, metric cards, card lists, bottom nav'),
    ('billnow-print-industry.css', 'Per-trade print blocks'),
    ('billnow-invoice.css',        'Sector invoice layouts and paper sizes'),
    ('billnow-nav.css',            'Drawer, sheets, sales filters'),
    ('billnow-brand.css',          'Brand palette, billing flow, stock screen'),
    ('billnow-pro.css',            'Desktop billing, printer setup, Rule 46 strip'),
    ('billnow-final.css',          'Scanner shell, khata dialog, install button'),
    ('billnow-ops.css',            'Range note, serial entry, edit banner, app health'),
]

RULE = '=' * 76


def bundle(parts, header):
    out = [header]
    for name, title in parts:
        path = os.path.join(SRC, name)
        if not os.path.exists(path):
            sys.exit(f'missing source module: src/{name}')
        out.append(f'/* {RULE}\n   {name.rsplit(".", 1)[0]}  —  {title}\n   {RULE} */\n')
        out.append(open(path, encoding='utf-8').read().rstrip() + '\n\n')
    return '\n'.join(out)


JS_HEADER = f"""/* ============================================================================
   Billnaw — application layer
   GENERATED by build.py from {len(JS)} modules in src/. Do not edit directly.

   Loaded after app.js and patches it at runtime. This was 15 separate <script>
   tags; each wrapped functions defined by the tags before it, and that ordering
   produced most of the bugs in this project: two floating bars built over a
   third, a camera preview rendered into a hidden box, readers using
   textContent where the writer used innerText.

   ORDER IS LOAD-BEARING. Sections appear in dependency order and must not be
   reordered. Each is a self-contained IIFE that talks to the others only
   through window.* globals.
   ========================================================================== */

"""

CSS_HEADER = f"""/* ============================================================================
   Billnaw — application styles
   GENERATED by build.py from {len(CSS)} stylesheets in src/. Do not edit directly.

   Loaded after styles.css. Cascade order is load-bearing: later sections
   deliberately override earlier ones at equal specificity.
   ========================================================================== */

"""


def main():
    js = bundle(JS, JS_HEADER)
    css = bundle(CSS, CSS_HEADER)
    check = '--check' in sys.argv

    for path, content in [(os.path.join(HERE, 'billnaw.js'), js),
                          (os.path.join(HERE, 'billnaw.css'), css)]:
        name = os.path.basename(path)
        if check:
            cur = open(path, encoding='utf-8').read() if os.path.exists(path) else ''
            if hashlib.sha256(cur.encode()).hexdigest() != hashlib.sha256(content.encode()).hexdigest():
                sys.exit(f'{name} is stale — run: python3 build.py')
            print(f'  {name} up to date')
        else:
            open(path, 'w', encoding='utf-8').write(content)
            print(f'  {name}  {len(content) / 1024:.0f} KB')

    if not check:
        print('\nRemember to bump CACHE_VERSION in sw.js, or devices keep the old copy.')


if __name__ == '__main__':
    main()
